[project]
name = "BAC1"
version = "2025.02-18"
description = "BACnet Scripting Framework for testing DDC Controls"
authors = [{name = "Christian Tremblay", email = "christian.tremblay@servisys.com"}]
readme = "README.md"
keywords = ["bacnet", "building", "automation", "test"]
dependencies=["BACpypes3", "colorama", "python-dotenv", "pytz", "aiosqlite"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.urls]
Homepage = "https://github.com/ChristianTremblay/BAC0"

[project.optional-dependencies]
extras = ["pandas", "influxdb_client[async]", "rich", "pytest-asyncio", "coverage"]

[tool.setuptools.package-data]
"BAC0.core.app" = ["device.json"]

[tool.setuptools.packages.find]
include = [
    "BAC1", 
    "BAC1.core", 
    "BAC1.core.app",
    "BAC1.core.app/device.json",
    "BAC1.core.io", 
    "BAC1.core.functions", 
    "BAC1.core.devices", 
    "BAC1.core.devices.local", 
    "BAC1.core.devices.mixins",
    "BAC1.core.proprietary_objects",
    "BAC1.core.utils", 
    "BAC1.db", 
    "BAC1.scripts", 
    "BAC1.tasks", 
    "BAC1.tools"]
namespaces = false

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "session"
